version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: reviews_db
    environment:
      POSTGRES_DB: reviews_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: